# How the software stores long-term data
storage:
  # The storage method
  #
  # Options:
  # - MySQL (remote)
  # - SQLite (local)
  method: 'sqlite'

  data:
    # Address and port of the remote database (if applicable)
    address: '127.0.0.1:3306'
    # The name of the database the software will store data in
    # If you're using remote options, this must be created beforehand
    database: 'headcount'
    # Table prefix for all software tables
    prefix: 'headcount_'
    # Database credentials (if applicable)
    username: ''
    password: ''

    # MongoDB options- obviously don't need to worry about these if not using MongoDB ;)
    mongodb:
      # Connection prefix for all Anti-VPN connections
      collection-prefix: ''
      # MongoDB ClientConnectionURI
      connection-uri: ''

  settings:
    # The maximum size of the database connection pool
    # Determines the max number of connections to the database
    max-pool-size: 2
    # The minimum size of the database connection pool
    # Determines the min number of connections kept alive to the database
    min-idle: 2
    # The maximum lifetime of a connection in the pool
    # Should be at least 30 seconds less than any database or infrastructure-imposed connection time limit
    max-lifetime: 1800000 # 30 minutes
    # The maximum number of milliseconds that the plugin will wait for a new connection from the pool before timing out
    timeout: 5000 # 5 seconds

    # Extra connection properties
    properties:
      unicode: true
      encoding: 'utf8'

# When true, logs some extra output to the console so you can see if/why things might be failing
debug: false

# GPIO information
gpio:
  # Sensor 1 on 5v
  # This is because more voltage = more range = more accuracy
  # We want the first sensor tripped to be accurate
  # This way we can account for ambient noise
  # When sensor 1 is tripped, it will act as the "trigger" for sensor 2
  sensor1:
    # The sensor voltage
    voltage: 5
    # The ADC pin for the sensor
    pin: 'A0'
    # The min value needed to count as a tripped sensor. Values between 0 and 1
    value: 0.4
  # The second sensor is on 3.3v
  # This is because we don't need it to be as accurate as sensor 1
  # Sensor 1 is the actual trigger. This sensor just ensures direction,
  # so is only taken into account when sensor 1 is tripped
  sensor2:
    # The sensor voltage
    voltage: 3.3
    # The ADC pin for the sensor
    pin: 'A1'
    # The min value needed to count as a tripped sensor. Values between 0 and 1
    value: 0.2

# Config version, no touchy plz
version: 1.0